font_family      JetBrainsMono Nerd Font
font_size        11.0

background_opacity         1.0
window_padding_width       10
hide_window_decorations    yes
confirm_os_window_close    0

cursor_shape               beam
cursor_blink_interval      0
cursor_trail               1
cursor_trail_decay         0.1 0.4
cursor_trail_start_threshold 2

shell_integration          no-cursor
enable_audio_bell          no
copy_on_select             clipboard
allow_remote_control       yes

map ctrl+insert            copy_to_clipboard
map shift+insert           paste_from_clipboard

tab_bar_edge               bottom
tab_bar_style              powerline
tab_powerline_style        slanted
tab_title_template         "{title}{' :({}):'.format(num_windows) if num_windows > 1 else ''}"

# BEGIN_KITTY_THEME
# Noctalia
include current-theme.conf
# END_KITTY_THEME
