-- =========================================================================
-- Modular Hyprland configuration (Lua loader, Hyprland 0.55+)
-- =========================================================================

local config_home = os.getenv("XDG_CONFIG_HOME") or (os.getenv("HOME") .. "/.config")
local hypr_dir = config_home .. "/hypr"

-- Make `require("noctalia")` resolve to ~/.config/hypr/noctalia.lua
-- (generated by Noctalia at theme time). Without this prepend, Lua's
-- default package.path rarely points at the user config dir.
package.path = hypr_dir .. "/?.lua;" .. package.path

-- Dynamic module loader (re-runs on every reload with no static cache)
local function load_module(name)
    dofile(hypr_dir .. "/modules/" .. name .. ".lua")
end

-- Load configuration modules in logical order
load_module("env")
load_module("monitors")
load_module("settings")
load_module("animations")
load_module("rules")
load_module("automation")
load_module("keybinds")
load_module("autostart")

-- Apply dynamic colors generated by Noctalia themes.
-- Use pcall to avoid a hard crash if the generated file is missing
-- (e.g. first boot before Noctalia has run once).
local ok, noctalia = pcall(require, "noctalia")
if ok and noctalia and noctalia.apply_theme then
    noctalia.apply_theme()

    -- Pyprland scratchpads usam group=deny, exigem nogroup_border explicito.
    -- Usa as cores exportadas pelo tema para acompanhar trocas de tema.
    hl.config({
        general = {
            col = {
                nogroup_border = noctalia.colors.surface,
                nogroup_border_active = noctalia.colors.primary,
            },
        },
    })
end
