[pyprland]
plugins = [
    "scratchpads",
    "gamemode",
    "expose",
]

# ── Scratchpads ────────────────────────────────────────────────────────

[scratchpads.terminal]
command = "kitty --class kitty-drop"
class = "kitty-drop"
animation = "fromTop"
size = "75% 60%"
margin = 50
lazy = true
pinned = true

[scratchpads.btop]
command = "kitty --class btop-scratch -e btop"
class = "btop-scratch"
animation = "fromTop"
size = "75% 60%"
lazy = true


[scratchpads.spotify]
command = "spotify-launcher"
class = "Spotify"
animation = "fromTop"
size = "60% 70%"
lazy = true
match_by = "class"
process_tracking = false

[scratchpads.steam]
command = "steam"
class = "steam"
animation = "fromTop"
size = "70% 80%"
lazy = true
match_by = "class"
process_tracking = false
close_on_hide = true
# ── Gamemode ────────────────────────────────────────────────────────────

[gamemode]
auto = true
patterns = ["steam_app_*", "gamescope*", "lutris*", "heroic*", "dota2", "cs2", "wine*"]
notify = true
